{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  datasource.yaml: |-
{{ .Files.Get "files/datasource.yml" | indent 4 }}
{{- end -}}
