{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: grafana-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  {{- with .Values.grafana.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: grafana
      protocol: TCP
      name: grafana
  selector:
    {{- include "bunkerweb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}
