apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  securityContext:
    fsGroup: 65534
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.3
          args:
            - -config.file=/etc/loki/loki-config.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /data/loki
      volumes:
        - name: config
          configMap:
            name: loki-config-{{ include "bunkerweb.fullname" . }}
        - name: data
          persistentVolumeClaim:
            claimName: loki-pvc-{{ include "bunkerweb.fullname" . }}
