apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promtail-rolebinding-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: promtail-role-{{ include "bunkerweb.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: promtail-sa-{{ include "bunkerweb.fullname" . }}
    namespace: {{ include "bunkerweb.namespace" . }}
