apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promtail
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.promtail.serviceAccount.name | default (printf "promtail-sa-%s" (include "bunkerweb.fullname" .)) }}
      containers:
        - name: promtail
          image: {{ .Values.promtail.repository }}:{{ .Values.promtail.tag }}
          imagePullPolicy: {{ .Values.promtail.pullPolicy }}
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
            - name: positions
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: promtail-config-{{ include "bunkerweb.fullname" . }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: positions
          emptyDir: {}
