{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bunkerweb.labels" . | nindent 8 }}
        bunkerweb.io/component: "redis"
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: Always
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          volumeMounts:
          - name: redis-config
            mountPath: /usr/local/etc/redis/
            readOnly: true
          - name: redis-data
            mountPath: /data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: redis-config
        configMap:
          name: redis-config-{{ include "bunkerweb.fullname" . }}
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-{{ include "bunkerweb.fullname" . }}
{{- end }}