apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bunkerweb.labels" . | nindent 8 }}
        {{- with .Values.scheduler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        bunkerweb.io/component: "scheduler"
    spec:
      serviceAccountName: {{ include "bunkerweb.fullname" . }}
      containers:
        - name: bunkerweb-scheduler
          image: {{ .Values.scheduler.repository }}:{{ .Values.scheduler.tag }}
          imagePullPolicy: {{ .Values.scheduler.pullPolicy }}
          {{- with .Values.scheduler.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12}}
          {{- end }}
          env:
            # Mandatory for k8s integration
            - name: KUBERNETES_MODE
              value: "yes"
            - name: DATABASE_URI
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.settings.existingSecret }}
                  key: database-uri
              {{- else }}
              value: "{{ include "bunkerweb.databaseUri" . }}"
              {{- end }}
            - name: SERVER_NAME
              value: ""
            - name: MULTISITE
              value: "yes"
            - name: DNS_RESOLVERS
              value: "{{ .Values.settings.misc.dnsResolvers }}"
            - name: API_WHITELIST_IP
              value: "{{ .Values.settings.misc.apiWhitelistIp }}"
            - name: BUNKERWEB_INSTANCES
              value: {{- if .Values.scheduler.extraEnvs | not | empty }}{{ .Values.scheduler.extraEnvs.BUNKERWEB_INSTANCES | default "" }}{{- else }}""{{- end }}
            {{- if .Values.settings.ui.wizard }}
            - name: UI_HOST
              value: "{{ include "bunkerweb.uiHost" . }}"
            {{- end }}
            {{- include "bunkerweb.redisEnv" . | nindent 12 }}
            {{- if .Values.scheduler.extraEnvs }}
              {{- toYaml .Values.scheduler.extraEnvs | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}